import movie1 from '../images/100 лет дизайна.png';
import movie2 from '../images/33 слова о дизайне.png';
import movie3 from '../images/Бег это свобода.png';
import movie4 from '../images/Бенкси.png';
import movie5 from '../images/Взрыв реальности.png';
import movie6 from '../images/История Игги.png';
import movie7 from '../images/Книготорговцы.png';
import movie8 from '../images/Когда я думаю в Германии ночью.png';
import movie9 from '../images/Маленькая девочка грустит.png';
import movie10 from '../images/Пи Джей Харви.png';
import movie11 from '../images/По волнам.png';
import movie12 from '../images/Соберись перед прыжком.png';


export const movies = [
  {
    country: 'США',
    director: 'К. Ноланд',
    duration: 107,
    year: '2012',
    description: 'Ноланд гений (почти как Кодзима)',
    image: movie1,
    trailerLink: 'https://kinopoisk.ru',
    thumbnail: movie1,
    owner: '1',
    movieId: 15,
    nameRU: '33 слова о дизайне',
    nameEN: '33 words about design',
    isSaved: false,
  },
  {
    country: 'Великобритания',
    director: 'А. Смит',
    duration: 120,
    year: '2015',
    description: 'Захватывающее путешествие в мир будущего и новых технологий',
    image: movie2,
    trailerLink: 'https://kinopoisk.ru/trailer2',
    thumbnail: movie2,
    owner: '2',
    movieId: 22,
    nameRU: 'Путешествие в будущее',
    nameEN: 'Journey to the Future',
    isSaved: true,
  },
  {
    country: 'Франция',
    director: 'Ж. Дюпон',
    duration: 95,
    year: '2010',
    description: 'Потрясающая история о любви и страсти',
    image: movie3,
    trailerLink: 'https://kinopoisk.ru/trailer3',
    thumbnail: movie3,
    owner: '1',
    movieId: 8,
    nameRU: 'Парижская любовь',
    nameEN: 'Love in Paris',
    isSaved: false,
  },
  {
    country: 'Испания',
    director: 'М. Гарсия',
    duration: 112,
    year: '2019',
    description: 'Драматический фильм о тяжелых испытаниях и жизненных перипетиях',
    image: movie4,
    trailerLink: 'https://kinopoisk.ru/trailer4',
    thumbnail: movie4,
    owner: '3',
    movieId: 9,
    nameRU: 'Судьба и слезы',
    nameEN: 'Fate and Tears',
    isSaved: true,
  },
  {
    country: 'Германия',
    director: 'М. Шмидт',
    duration: 98,
    year: '2017',
    description: 'Увлекательный фильм о тайнах и загадках мира',
    image: movie5,
    trailerLink: 'https://kinopoisk.ru/trailer5',
    thumbnail: movie5,
    owner: '1',
    movieId: 10,
    nameRU: 'Тайны мира',
    nameEN: 'Mysteries of the World',
    isSaved: false,
  },
  {
    country: 'Италия',
    director: 'Л. Бертолуччи',
    duration: 130,
    year: '2005',
    description: 'История любви и предательства',
    image: movie6,
    trailerLink: 'https://kinopoisk.ru/trailer6',
    thumbnail: movie6,
    owner: '2',
    movieId: 11,
    nameRU: 'Последнее предательство',
    nameEN: 'The Last Betrayal',
    isSaved: true,
  },
  {
    country: 'Япония',
    director: 'К. Танака',
    duration: 115,
    year: '2018',
    description: 'Фильм о самураях и чести',
    image: movie7,
    trailerLink: 'https://kinopoisk.ru/trailer7',
    thumbnail: movie7,
    owner: '3',
    movieId: 12,
    nameRU: 'Самурайское сокровище',
    nameEN: 'Samurai Treasure',
    isSaved: false,
  },
  {
    country: 'Канада',
    director: 'Д. Смит',
    duration: 105,
    year: '2016',
    description: 'Забавная комедия о молодежной жизни',
    image: movie8,
    trailerLink: 'https://kinopoisk.ru/trailer8',
    thumbnail: movie8,
    owner: '1',
    movieId: 13,
    nameRU: 'Молодость в канадском стиле',
    nameEN: 'Youth in Canadian Style',
    isSaved: true,
  },
  {
    country: 'Бразилия',
    director: 'М. Родригес',
    duration: 122,
    year: '2014',
    description: 'Великолепный фильм о приключениях и опасностях',
    image: movie9,
    trailerLink: 'https://kinopoisk.ru/trailer9',
    thumbnail: movie9,
    owner: '2',
    movieId: 14,
    nameRU: 'Бразильские приключения',
    nameEN: 'Brazilian Adventures',
    isSaved: false,
  },
  {
    country: 'Россия',
    director: 'И. Петров',
    duration: 95,
    year: '2019',
    description: 'Трогательный фильм о дружбе и верности',
    image: movie10,
    trailerLink: 'https://kinopoisk.ru/trailer10',
    thumbnail: movie10,
    owner: '3',
    movieId: 16,
    nameRU: 'Друзья навсегда',
    nameEN: 'Friends Forever',
    isSaved: true,
  },
  {
    country: 'Франция',
    director: 'Ж. Лепетит',
    duration: 110,
    year: '2013',
    description: 'Фильм о приключениях и открытиях',
    image: movie11,
    trailerLink: 'https://kinopoisk.ru/trailer11',
    thumbnail: movie11,
    owner: '1',
    movieId: 17,
    nameRU: 'По следам исследователей',
    nameEN: 'In the Footsteps of Explorers',
    isSaved: false,
  },
  {
    country: 'Испания',
    director: 'П. Рамирес',
    duration: 118,
    year: '2011',
    description: 'Таинственный фильм о загадках и мистике',
    image: movie12,
    trailerLink: 'https://kinopoisk.ru/trailer12',
    thumbnail: movie12,
    owner: '2',
    movieId: 18,
    nameRU: 'Тайны и мистика',
    nameEN: 'Secrets and Mysteries',
    isSaved: true,
  }];



  